version: "3.9"

services:
  userbackend:
    build: ./server/userBackend
    image: userbackend
    container_name: userbackend_server
    ports:
      - "8084:8084"

  itembackend:
    build: ./server/itemBackend
    image: itembackend
    container_name: itembackend_server
    ports:
      - "8081:8081"
    depends_on:
      - userbackend

  cartbackend:
    build: ./server/cartBackend
    image: cartbackend
    container_name: cartbackend_server
    ports:
      - "8083:8083"
    depends_on:
      - userbackend
      - itembackend

  paymentbackend:
    build: ./server/paymentBackend
    image: paymentbackend
    container_name: paymentbackend_server
    ports:
      - "8082:8082"
    depends_on:
      - userbackend
      - cartbackend

  gateway:
    build: ./server/gateway
    image: gateway
    container_name: gateway_server
    ports:
      - "8070:8070"
    depends_on:
      - userbackend
      - itembackend
      - cartbackend
      - paymentbackend

  frontend:
    build: ./client
    image: client
    container_name: client_server
    ports:
      - "3000:3000"
    depends_on:
      - gateway