apiVersion: v1
kind: Service
metadata:
  name: vedra
spec:
  ports:
  - name: user-service
    port: 8084
    protocol: TCP
    targetPort: 8084
  - name: item-service
    port: 8081
    protocol: TCP
    targetPort: 8081
  - name: order-service
    port: 8083
    protocol: TCP
    targetPort: 8083
  - name: payment-service
    port: 8082
    protocol: TCP
    targetPort: 8082
  - name: gateway-service
    port: 8070
    protocol: TCP
    targetPort: 8070
  - name: client-service
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: vedra
  type: LoadBalancer
status:
  loadBalancer: {}
 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vedra
  name: vedra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vedra
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: vedra
    spec:
      containers:
      - name: user-service
        image: it21008146/user-service
        imagePullPolicy: Always
        ports:
        - containerPort: 8084
          protocol: TCP
        resources: {}
      - name: item-service
        image: it21008146/item-service
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
          protocol: TCP
        resources: {}
      - name: order-service
        image: it21008146/order-service
        imagePullPolicy: Always
        ports:
        - containerPort: 8083
          protocol: TCP
        resources: {}
      - name: payment-service
        image: it21008146/payment-service
        imagePullPolicy: Always
        ports:
        - containerPort: 8082
          protocol: TCP
        resources: {} 
      - name: gateway-service
        image: it21008146/gateway-service
        imagePullPolicy: Always
        ports:
        - containerPort: 8070
          protocol: TCP
        resources: {}
      - name: frontend-service
        image: it21008146/frontend-service
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          protocol: TCP
        resources: {}       
      restartPolicy: Always
status: {}

# kubectl apply -f herbcollab.yaml
# kubectl delete -f herbcollab.yaml